{
  "formatVersion": "1.1",
  "component": {
    "group": "net.moddingplayground.toymaker",
    "module": "toymaker-fabric",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.3.jar",
          "url": "toymaker-fabric-1.1.3.jar",
          "size": 126263,
          "sha512": "4680164715c595bfb9c96a51b571503e7bc9167b1783a4b49e561daf04bac92a704cb034f9e11aacec27a72d63fba8e37ca27fbe8214e8c60f476f7cbf8586c3",
          "sha256": "9b9cddaa68c270a825c4195e5ece6e8c0163504c36863cd618ea41f07c32b787",
          "sha1": "d41f4e18dac0c283668651849dc1dc58048ce353",
          "md5": "4f5d682be9cbb1ce74e873fb31344b91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.2+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "toymaker-fabric-1.1.3.jar",
          "url": "toymaker-fabric-1.1.3.jar",
          "size": 126263,
          "sha512": "4680164715c595bfb9c96a51b571503e7bc9167b1783a4b49e561daf04bac92a704cb034f9e11aacec27a72d63fba8e37ca27fbe8214e8c60f476f7cbf8586c3",
          "sha256": "9b9cddaa68c270a825c4195e5ece6e8c0163504c36863cd618ea41f07c32b787",
          "sha1": "d41f4e18dac0c283668651849dc1dc58048ce353",
          "md5": "4f5d682be9cbb1ce74e873fb31344b91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.3-sources.jar",
          "url": "toymaker-fabric-1.1.3-sources.jar",
          "size": 64239,
          "sha512": "015aeb3fe8c1349f05076171ccfb32008df3b9bddf4af4a75352edd78f2b5ac689f35428fa7de47e6c7758feb6987f5af4a5d49fa553afa700569ebfce9d397b",
          "sha256": "431436d4a8b59c217b05fa6d009ad214ee25c1af355d56e6d862252b00f6bcde",
          "sha1": "7b300f822980e6925de371b528e716ad42d79b72",
          "md5": "84f354b786b2e06fce306f692fd6d04f"
        }
      ]
    }
  ]
}
