{
  "formatVersion": "1.1",
  "component": {
    "group": "net.moddingplayground.toymaker",
    "module": "toymaker-fabric",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.2.jar",
          "url": "toymaker-fabric-1.1.2.jar",
          "size": 126630,
          "sha512": "45ce9d2c377e6eaef63233d027b83d2816d2baed139134b65cdd3f5bd2279821bac582ab338adf5c1f85580b1d141b853b11107c2eee92b51a916fe8deacab87",
          "sha256": "160aae1d0f2f03f0587a53e7314bb98155447477ec9423ba5262b348293337d4",
          "sha1": "a5b72f9e3bee503e435c59271ac16187ef0ba2b8",
          "md5": "79733ce3ef6165e106dcb20fa28d1969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.2+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "toymaker-fabric-1.1.2.jar",
          "url": "toymaker-fabric-1.1.2.jar",
          "size": 126630,
          "sha512": "45ce9d2c377e6eaef63233d027b83d2816d2baed139134b65cdd3f5bd2279821bac582ab338adf5c1f85580b1d141b853b11107c2eee92b51a916fe8deacab87",
          "sha256": "160aae1d0f2f03f0587a53e7314bb98155447477ec9423ba5262b348293337d4",
          "sha1": "a5b72f9e3bee503e435c59271ac16187ef0ba2b8",
          "md5": "79733ce3ef6165e106dcb20fa28d1969"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.2-sources.jar",
          "url": "toymaker-fabric-1.1.2-sources.jar",
          "size": 64356,
          "sha512": "460ab24ded192879526fa980ef219e2937ef7f87c7dc95ed474b572e5d116bf777f2080c784b0acfface35903b5c24489ed2bc907c913350f116f23605ffc70e",
          "sha256": "f9dc88ef3b890ff1bfcf8ee692e53243dc3a27bb7fb0586f70f40e161c32c3fa",
          "sha1": "76516146d74a97af4f3b181201026fd24d7994e9",
          "md5": "671c4b4e02fd9c1a81b83a50b639027a"
        }
      ]
    }
  ]
}
