{
  "formatVersion": "1.1",
  "component": {
    "group": "net.moddingplayground.toymaker",
    "module": "toymaker-fabric",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.2.0.jar",
          "url": "toymaker-fabric-1.2.0.jar",
          "size": 126632,
          "sha512": "43168b6dbd0e78691b6e74757cd5719b0d564f657189009e0582bcf310b6356c55bcfc679b73d8dd1a9b9ba7c26ae7d1b4b032000fdb78c02f22c98dc781a56d",
          "sha256": "4ca1375de2edb467515b4b35b1f3c6081c61cdd6664823c5879a27c06d1771eb",
          "sha1": "00c562289f206ab8b9e674a15ef69f78bf561cc7",
          "md5": "15333dedb947812410967e4fae640e97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.2+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "toymaker-fabric-1.2.0.jar",
          "url": "toymaker-fabric-1.2.0.jar",
          "size": 126632,
          "sha512": "43168b6dbd0e78691b6e74757cd5719b0d564f657189009e0582bcf310b6356c55bcfc679b73d8dd1a9b9ba7c26ae7d1b4b032000fdb78c02f22c98dc781a56d",
          "sha256": "4ca1375de2edb467515b4b35b1f3c6081c61cdd6664823c5879a27c06d1771eb",
          "sha1": "00c562289f206ab8b9e674a15ef69f78bf561cc7",
          "md5": "15333dedb947812410967e4fae640e97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.2.0-sources.jar",
          "url": "toymaker-fabric-1.2.0-sources.jar",
          "size": 64335,
          "sha512": "c965ff41dca122e58a4e2870ee652ab860cd2e3d976bc09d53f707493ca00209e9f43710e5abe73cf210535929b0af95fe1b15934daf9a853833b89e9ea3fce5",
          "sha256": "7eccfea7c0577a97665c9aaabbd6850ba61ab8d798e57ff014c691303c9e1ae3",
          "sha1": "2d8e251159830473eb9e1388229961096efa999a",
          "md5": "7073264bfe5907820814bf326ddf2fb5"
        }
      ]
    }
  ]
}
