{
  "formatVersion": "1.1",
  "component": {
    "group": "net.moddingplayground.toymaker",
    "module": "toymaker-fabric",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.1.jar",
          "url": "toymaker-fabric-1.1.1.jar",
          "size": 123460,
          "sha512": "18dc43813985065ad86f4c7bb83ca1da43d5dac08f1293901cc31d2ca9acba6b60a9552243058d695c9a6939d18573f89fb09af0e7a60d75f2574d78984bb45c",
          "sha256": "08ffa71c411f62999d29878f9287c3759948182b3a1d360d3171a8824aa1c56e",
          "sha1": "41c2b361d346393b536abb37d3c6c2254581d73f",
          "md5": "80e8274070698bdbf6073e7cf1aecd6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.2+1.18"
          }
        }
      ],
      "files": [
        {
          "name": "toymaker-fabric-1.1.1.jar",
          "url": "toymaker-fabric-1.1.1.jar",
          "size": 123460,
          "sha512": "18dc43813985065ad86f4c7bb83ca1da43d5dac08f1293901cc31d2ca9acba6b60a9552243058d695c9a6939d18573f89fb09af0e7a60d75f2574d78984bb45c",
          "sha256": "08ffa71c411f62999d29878f9287c3759948182b3a1d360d3171a8824aa1c56e",
          "sha1": "41c2b361d346393b536abb37d3c6c2254581d73f",
          "md5": "80e8274070698bdbf6073e7cf1aecd6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toymaker-fabric-1.1.1-sources.jar",
          "url": "toymaker-fabric-1.1.1-sources.jar",
          "size": 61186,
          "sha512": "388b86a0afe445bb11bbd0c7fc1aba4016682a2774ad1be51cf91404be3fbfa83c44c9160cde48cd940c0641f851a5a94088c2e85a16eddb991e308d5afb434d",
          "sha256": "fcf8a8e27ff869a5a4e76f9b2c78f4cac1c49f14a008dedca1fa7f3e6ba0a72e",
          "sha1": "d2b21ab19c7a666830e21e773e6ccdb68465b636",
          "md5": "1922aea2e3239484422b36c889d2c67e"
        }
      ]
    }
  ]
}
